backend:
  name: github
  repo: chapabu/chapabu.codes
publish_mode: editorial_workflow
media_folder: 'src/images/uploads'
public_folder: 'images/uploads'
media_library:
  name: cloudinary
  config:
    cloud_name: chapabu
    api_key: 185178558152674
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Homepage'
        create: false
        delete: false
        file: content/home.yml
        fields:
          - label: Permalink
            name: permalinee
            widget: hidden
            default: /
          - label: Layout
            name: layout
            widget: hidden
            default: layouts/home.njk
          - label: Avatar
            name: avatar
            widget: image
          - label: Blurb
            name: blurb
            widget: markdown
          - label: Metadata
            name: metadata
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Social image
                name: social_image
                widget: image
                required: false
  - name: 'post'
    label: 'Posts'
    folder: 'src/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
      - label: Publish date
        name: publish_date
        widget: datetime
      - label: Image
        name: image
        widget: image
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Metadata
        name: metadata
        widget: object
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: string
          - label: Social image
            name: social_image
            widget: image
            required: false
  # - name: 'external_post'
  #   label: 'External posts'
